// Code generated by go2go; DO NOT EDIT.


//line sort_slice_dps.go2:1
package sort_slice_dps

//line sort_slice_dps.go2:1
import (
//line sort_slice_dps.go2:1
 "fmt"
//line sort_slice_dps.go2:1
 "log"
//line sort_slice_dps.go2:1
 "math/rand"
//line sort_slice_dps.go2:1
 "testing"
//line sort_slice_dps.go2:1
)

//line sort_slice_dps.go2:6
const maxRunCount = 67

//line sort_slice_dps.go2:12
const quicksortThreshold = 286

//line sort_slice_dps.go2:18
const insertionSortThreshold = 47

//line sort_slice_dps.go2:18
type Importable୦ int

//line sort_slice_dps.go2:18
var _ = fmt.Errorf
//line sort_slice_dps.go2:18
var _ = log.Fatal
//line sort_slice_dps.go2:18
var _ = rand.ExpFloat64
//line sort_slice_dps.go2:18
var _ = testing.AllocsPerRun
